"""Add user isolation with automatic defaults

Revision ID: 903ec58eddde
Revises: bc793d7d873d
Create Date: 2025-09-21 10:42:43.693704

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "903ec58eddde"
down_revision = "bc793d7d873d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("personas", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.create_foreign_key("fk_personas_user_id", "user", ["user_id"], ["id"])

    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.create_foreign_key("fk_resources_user_id", "user", ["user_id"], ["id"])
        batch_op.drop_column("upload_user_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.add_column(sa.Column("upload_user_id", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("fk_resources_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("personas", schema=None) as batch_op:
        batch_op.drop_constraint("fk_personas_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
