"""Add session_id to chat_history for conversation memory

Revision ID: f390eca2c13a
Revises: 8544fa487459
Create Date: 2025-09-19 23:11:42.455092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f390eca2c13a'
down_revision = '8544fa487459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
